name: build and production deploy

on: push
  # push:
    # branches:
      # - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore dependency cache
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependency
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        # run: npx netlify-cli deploy -d pubilc --prod -a ${{ secrets.NETLIFY_AUTH_TOKEN }} -s ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy -d pubilc -a ${{ secrets.NETLIFY_AUTH_TOKEN }} -s ${{ secrets.NETLIFY_SITE_ID }}
